import { useEffect, useMemo, useState } from 'react'
import { Edit2, Loader2, Plus, Search, ToggleLeft, ToggleRight, Trash2, X } from 'lucide-react'
import Modal, { Field, Input, Toast } from '@/components/Modal'
import { AccionApi, controlAccesoApi } from './services/control-acceso.api'


export default function AccionesPage() {
  const [items, setItems] = useState<AccionApi[]>([])
  const [search, setSearch] = useState('')
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [modalOpen, setModalOpen] = useState(false)
  const [editingId, setEditingId] = useState<number | null>(null)
  const [form, setForm] = useState({ codigo: '', nombre: '', descripcion: '', estado: 'ACTIVO' as 'ACTIVO' | 'INACTIVO' })
  const [toast, setToast] = useState<{ message: string; type: 'success' | 'error' } | null>(null)

  const load = async () => { setLoading(true); try { setItems((await controlAccesoApi.listarAcciones()).data) } catch (error) { setToast({ message: error instanceof Error ? error.message : 'No se pudieron cargar las acciones.', type: 'error' }) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const filtered = useMemo(() => { const q = search.toLowerCase().trim(); return !q ? items : items.filter((item) => [item.codigo, item.nombre, item.descripcion ?? ''].some((value) => value.toLowerCase().includes(q))) }, [items, search])

  const openCreate = () => { setEditingId(null); setForm({ codigo: '', nombre: '', descripcion: '', estado: 'ACTIVO' }); setModalOpen(true) }
  const openEdit = (item: AccionApi) => { setEditingId(item.idAccion); setForm({ codigo: item.codigo, nombre: item.nombre, descripcion: item.descripcion ?? '', estado: item.estado }); setModalOpen(true) }
  const submit = async () => { if (!form.codigo.trim() || !form.nombre.trim()) return; setSaving(true); try { const payload = { ...form, descripcion: form.descripcion || null }; const saved = editingId === null ? await controlAccesoApi.crearAccion(payload) : await controlAccesoApi.actualizarAccion(editingId, payload); setItems((current) => editingId === null ? [...current, saved] : current.map((item) => item.idAccion === editingId ? saved : item)); setModalOpen(false); setToast({ message: 'Acción guardada.', type: 'success' }) } catch (error) { setToast({ message: error instanceof Error ? error.message : 'No se pudo guardar.', type: 'error' }) } finally { setSaving(false) } }
  const toggle = async (item: AccionApi) => { try { const updated = await controlAccesoApi.actualizarAccion(item.idAccion, { estado: item.estado === 'ACTIVO' ? 'INACTIVO' : 'ACTIVO' }); setItems((current) => current.map((value) => value.idAccion === item.idAccion ? updated : value)) } catch (error) { setToast({ message: error instanceof Error ? error.message : 'No se pudo cambiar el estado.', type: 'error' }) } }
  const remove = async (item: AccionApi) => { if (!window.confirm(`¿Inactivar ${item.nombre}?`)) return; try { const updated = await controlAccesoApi.inactivarAccion(item.idAccion); setItems((current) => current.map((value) => value.idAccion === item.idAccion ? updated : value)) } catch (error) { setToast({ message: error instanceof Error ? error.message : 'No se pudo inactivar.', type: 'error' }) } }

  return <div className="p-6 space-y-5 overflow-y-auto">
    <div className="flex gap-3"><div className="flex items-center gap-2 px-3 py-2.5 rounded flex-1" style={{ background: 'var(--card)', border: '1px solid var(--border)' }}><Search size={13} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar acciones..." className="bg-transparent outline-none text-xs w-full" />{search && <button onClick={() => setSearch('')}><X size={12} /></button>}</div><button onClick={openCreate} className="flex items-center gap-2 px-4 py-2.5 rounded text-xs font-semibold" style={{ background: 'var(--gold)', color: 'var(--primary-foreground)' }}><Plus size={13} /> Nueva acción</button></div>
    <div className="rounded-lg overflow-hidden" style={{ background: 'var(--card)', border: '1px solid var(--border)' }}>{loading ? <div className="py-16 flex justify-center"><Loader2 className="animate-spin" /></div> : <table className="w-full text-xs"><thead><tr style={{ background: 'var(--secondary)' }}>{['Acción', 'Descripción', 'Permisos', 'Estado', 'Acciones'].map((h) => <th key={h} className="text-left px-5 py-3 uppercase tracking-widest" style={{ color: 'var(--muted-foreground)', fontSize: 9 }}>{h}</th>)}</tr></thead><tbody>{filtered.map((item) => <tr key={item.idAccion} style={{ borderBottom: '1px solid rgba(255,255,255,0.04)' }}><td className="px-5 py-4"><p>{item.nombre}</p><p className="text-[10px]" style={{ color: 'var(--muted-foreground)' }}>{item.codigo}</p></td><td className="px-5 py-4" style={{ color: 'var(--muted-foreground)' }}>{item.descripcion || '—'}</td><td className="px-5 py-4">{item.totalPermisos}</td><td className="px-5 py-4" style={{ color: item.estado === 'ACTIVO' ? '#4ade80' : '#f87171' }}>{item.estado}</td><td className="px-5 py-4"><div className="flex gap-2"><button onClick={() => openEdit(item)}><Edit2 size={13} /></button><button onClick={() => void toggle(item)}>{item.estado === 'ACTIVO' ? <ToggleRight size={15} /> : <ToggleLeft size={15} />}</button><button onClick={() => void remove(item)}><Trash2 size={13} /></button></div></td></tr>)}</tbody></table>}</div>
    <Modal open={modalOpen} onClose={() => setModalOpen(false)} title={editingId === null ? 'Nueva acción' : 'Editar acción'} size="sm"><div className="space-y-4"><Field label="Código" required><Input value={form.codigo} onChange={(event) => setForm((current) => ({ ...current, codigo: event.target.value }))} /></Field><Field label="Nombre" required><Input value={form.nombre} onChange={(event) => setForm((current) => ({ ...current, nombre: event.target.value }))} /></Field><Field label="Descripción"><Input value={form.descripcion} onChange={(event) => setForm((current) => ({ ...current, descripcion: event.target.value }))} /></Field><Field label="Estado"><select value={form.estado} onChange={(event) => setForm((current) => ({ ...current, estado: event.target.value as 'ACTIVO' | 'INACTIVO' }))} className="w-full rounded px-3 py-2.5 text-xs" style={{ background: 'var(--card)', border: '1px solid var(--border)', color: 'var(--foreground)' }}><option value="ACTIVO">ACTIVO</option><option value="INACTIVO">INACTIVO</option></select></Field></div><div className="flex justify-end gap-3 mt-6 pt-4"><button onClick={() => setModalOpen(false)}>Cancelar</button><button onClick={() => void submit()} disabled={saving} className="px-5 py-2.5 rounded text-xs font-semibold" style={{ background: 'var(--gold)', color: 'var(--primary-foreground)' }}>Guardar</button></div></Modal>
    {toast && <Toast message={toast.message} type={toast.type} onClose={() => setToast(null)} />}
  </div>
}
