import { useEffect, useState } from 'react'
import { Edit2, Loader2, Plus, ToggleLeft, ToggleRight, Trash2 } from 'lucide-react'
import Modal, { Field, Toast } from '@/components/Modal'
import { AccionApi, controlAccesoApi, ModuloApi, PermisoApi } from './services/control-acceso.api'


export default function PermisosPage() {
  const [items, setItems] = useState<PermisoApi[]>([])
  const [modules, setModules] = useState<ModuloApi[]>([])
  const [actions, setActions] = useState<AccionApi[]>([])
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [modalOpen, setModalOpen] = useState(false)
  const [editingId, setEditingId] = useState<number | null>(null)
  const [form, setForm] = useState({ idModulo: '', idAccion: '', estado: 'ACTIVO' as 'ACTIVO' | 'INACTIVO' })
  const [toast, setToast] = useState<{ message: string; type: 'success' | 'error' } | null>(null)

  const load = async () => { setLoading(true); try { const [p, m, a] = await Promise.all([controlAccesoApi.listarPermisos(), controlAccesoApi.listarModulos(), controlAccesoApi.listarAcciones()]); setItems(p.data); setModules(m.data.filter((x) => x.estado === 'ACTIVO')); setActions(a.data.filter((x) => x.estado === 'ACTIVO')) } catch (error) { setToast({ message: error instanceof Error ? error.message : 'No se pudo cargar.', type: 'error' }) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const openCreate = () => { setEditingId(null); setForm({ idModulo: '', idAccion: '', estado: 'ACTIVO' }); setModalOpen(true) }
  const openEdit = (item: PermisoApi) => { setEditingId(item.idPermiso); setForm({ idModulo: String(item.idModulo), idAccion: String(item.idAccion), estado: item.estado }); setModalOpen(true) }
  const submit = async () => { if (!form.idModulo || !form.idAccion) return; setSaving(true); try { const payload = { idModulo: Number(form.idModulo), idAccion: Number(form.idAccion), estado: form.estado }; const saved = editingId === null ? await controlAccesoApi.crearPermiso(payload) : await controlAccesoApi.actualizarPermiso(editingId, payload); setItems((current) => editingId === null ? [...current, saved] : current.map((item) => item.idPermiso === editingId ? saved : item)); setModalOpen(false) } catch (error) { setToast({ message: error instanceof Error ? error.message : 'No se pudo guardar.', type: 'error' }) } finally { setSaving(false) } }
  const toggle = async (item: PermisoApi) => { try { const updated = await controlAccesoApi.actualizarPermiso(item.idPermiso, { estado: item.estado === 'ACTIVO' ? 'INACTIVO' : 'ACTIVO' }); setItems((current) => current.map((value) => value.idPermiso === item.idPermiso ? updated : value)) } catch (error) { setToast({ message: error instanceof Error ? error.message : 'No se pudo cambiar el estado.', type: 'error' }) } }
  const remove = async (item: PermisoApi) => { if (!window.confirm(`¿Inactivar ${item.modulo.nombre} + ${item.accion.nombre}?`)) return; try { const updated = await controlAccesoApi.inactivarPermiso(item.idPermiso); setItems((current) => current.map((value) => value.idPermiso === item.idPermiso ? updated : value)) } catch (error) { setToast({ message: error instanceof Error ? error.message : 'No se pudo inactivar.', type: 'error' }) } }

  return <div className="p-6 space-y-5 overflow-y-auto">
    <div className="flex justify-end"><button onClick={openCreate} className="flex items-center gap-2 px-4 py-2.5 rounded text-xs font-semibold" style={{ background: 'var(--gold)', color: 'var(--primary-foreground)' }}><Plus size={13} /> Nuevo permiso</button></div>
    <div className="rounded-lg overflow-hidden" style={{ background: 'var(--card)', border: '1px solid var(--border)' }}>{loading ? <div className="py-16 flex justify-center"><Loader2 className="animate-spin" /></div> : <table className="w-full text-xs"><thead><tr style={{ background: 'var(--secondary)' }}>{['Módulo', 'Acción', 'Roles', 'Estado', 'Acciones'].map((h) => <th key={h} className="text-left px-5 py-3 uppercase tracking-widest" style={{ color: 'var(--muted-foreground)', fontSize: 9 }}>{h}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={item.idPermiso} style={{ borderBottom: '1px solid rgba(255,255,255,0.04)' }}><td className="px-5 py-4">{item.modulo.nombre}</td><td className="px-5 py-4">{item.accion.nombre}</td><td className="px-5 py-4">{item.totalRoles}</td><td className="px-5 py-4" style={{ color: item.estado === 'ACTIVO' ? '#4ade80' : '#f87171' }}>{item.estado}</td><td className="px-5 py-4"><div className="flex gap-2"><button onClick={() => openEdit(item)}><Edit2 size={13} /></button><button onClick={() => void toggle(item)}>{item.estado === 'ACTIVO' ? <ToggleRight size={15} /> : <ToggleLeft size={15} />}</button><button onClick={() => void remove(item)}><Trash2 size={13} /></button></div></td></tr>)}</tbody></table>}</div>
    <Modal open={modalOpen} onClose={() => setModalOpen(false)} title={editingId === null ? 'Nuevo permiso' : 'Editar permiso'} size="sm"><div className="space-y-4"><Field label="Módulo" required><select value={form.idModulo} onChange={(event) => setForm((current) => ({ ...current, idModulo: event.target.value }))} className="w-full rounded px-3 py-2.5 text-xs" style={{ background: 'var(--card)', border: '1px solid var(--border)', color: 'var(--foreground)' }}><option value="">Seleccionar...</option>{modules.map((item) => <option key={item.idModulo} value={item.idModulo}>{item.nombre}</option>)}</select></Field><Field label="Acción" required><select value={form.idAccion} onChange={(event) => setForm((current) => ({ ...current, idAccion: event.target.value }))} className="w-full rounded px-3 py-2.5 text-xs" style={{ background: 'var(--card)', border: '1px solid var(--border)', color: 'var(--foreground)' }}><option value="">Seleccionar...</option>{actions.map((item) => <option key={item.idAccion} value={item.idAccion}>{item.nombre}</option>)}</select></Field><Field label="Estado"><select value={form.estado} onChange={(event) => setForm((current) => ({ ...current, estado: event.target.value as 'ACTIVO' | 'INACTIVO' }))} className="w-full rounded px-3 py-2.5 text-xs" style={{ background: 'var(--card)', border: '1px solid var(--border)', color: 'var(--foreground)' }}><option value="ACTIVO">ACTIVO</option><option value="INACTIVO">INACTIVO</option></select></Field></div><div className="flex justify-end gap-3 mt-6 pt-4"><button onClick={() => setModalOpen(false)}>Cancelar</button><button onClick={() => void submit()} disabled={saving} className="px-5 py-2.5 rounded text-xs font-semibold" style={{ background: 'var(--gold)', color: 'var(--primary-foreground)' }}>Guardar</button></div></Modal>
    {toast && <Toast message={toast.message} type={toast.type} onClose={() => setToast(null)} />}
  </div>
}
